# Generated by Django 3.1.7 on 2021-04-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_memes_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='meme',
            field=models.ImageField(upload_to='memes/'),
        ),
    ]
