# Generated by Django 3.1.7 on 2021-04-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210403_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='memes',
            name='usr_img',
            field=models.CharField(max_length=124, null=True),
        ),
    ]
