# Generated by Django 3.1.7 on 2021-04-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_memes_usr_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='usr_img',
            field=models.CharField(max_length=124, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='number_of_memes',
            field=models.IntegerField(default=0),
        ),
    ]
