# Generated by Django 3.1.7 on 2021-04-03 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20210403_1930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
